### PR TITLE
Bump JupyterCAD to `3.0.0a6`

### PR DESCRIPTION
**Pull request by arjxn-py**
Should address https://github.com/jupytercad/JupyterCAD/issues/582

### CODE REVIEW

**Comment by martinRenou** [comment]
The CI will fail, https://github.com/jupytercad/JupyterCAD-OpenVSP/pull/7 will fix it

**Comment by arjxn-py** [comment]
`Preparing metadata (pyproject.toml): finished with status 'error'` I wonder what's wrong exactly?

**Comment by martinRenou** [comment]
The actual error message is somewhere else (it's always annoying to find the actual error message with hatch):

```
src/index.ts(4,8): error TS2307: Cannot find module '@jupyter/docprovider' or its corresponding type declarations
```

Seems to be a missing dependency on docprovider

**Comment by arjxn-py** [comment]
I see, I'm on it. Thanks

**Comment by arjxn-py** [comment]
Failed again on `Parsed an error from text content: undefined Plugin 'jupytercad_openvsp:plugin' failed to activate.` Maybe 

https://github.com/jupytercad/JupyterCAD-OpenVSP/blob/241b75d8bc699fbbdcd1d9ce00444ff5983c50f0/src/index.ts#L28

**Comment by martinRenou** [comment]
When a plugin fails to activate, there is usually another error prior to that in the JavaScript console that tells you what caused the failure. Have you tried locally?

**Comment by arjxn-py** [comment]
> When a plugin fails to activate, there is usually another error prior to that in the JavaScript console that tells you what caused the failure. Have you tried locally?

Yeah, just did. It says:

image

EDIT- i reuploaded the image with more logs

**Comment by trungleduc** [comment]
you need to update the shared packages in `package.json`, like in this commit https://github.com/jupytercad/JupyterCAD-FreeCAD/pull/17/commits/7e390add03867353cceeff45f870df57849f8888#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by arjxn-py** [comment]
> you need to update the shared packages in `package.json`

Thanks @trungleduc, done in [`2b77531`](https://github.com/jupytercad/JupyterCAD-OpenVSP/pull/8/commits/2b775316c688c1a145cef675094016feaf8e9fbd)

**Comment by arjxn-py** [comment]
Tested locally too, it's working fine.

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
